version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: psql_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: leader
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  webapp:
    build: .
    container_name: go_webapp
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:strongpassword@db:5432/mydb?sslmode=disable

volumes:
  pgdata:
