// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

type User struct {
	ID       int64
	Name     string
	Email    string
	Password string
}

type UserMessage struct {
	ID      int64
	Name    string
	Email   string
	Message string
}
