// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Email struct {
	ID        int64
	WebsiteID pgtype.Int8
	Email     string
	Date      pgtype.Timestamptz
}

type SearchHistory struct {
	ID         int64
	UserID     pgtype.Int8
	Keyword    string
	SearchTime pgtype.Timestamptz
}

type User struct {
	ID       int64
	Name     string
	Email    string
	Password string
}

type UserMessage struct {
	ID      int64
	Name    string
	Email   string
	Message string
}

type Website struct {
	ID              int64
	SearchHistoryID pgtype.Int8
	Url             string
}
